[package]
name = "ldap-matrix-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
matrix-sdk = "0.6.2"
serde = "1.0.152"
serde_yaml = "0.9.17"
clap = { version = "4.1.6", features = ["derive"] }
log = "0.4.17"
env_logger = "0.10.0"

[dependencies.ldap3]
version = "0.11.1"
